import { Field } from 'payload'

export const SeoFields: Field[] = [
    { name: 'metadataBase', label: 'Metadata Base', type: 'text' },
    {
        name: 'title',
        label: 'Title',
        type: 'group',
        fields: [
            { name: 'default', type: 'text', label: 'Default' },
            { name: 'template', type: 'text', label: 'Template' },
            { name: 'absolute', type: 'text', label: 'Absolute' },
        ],
    },
    { name: 'description', type: 'textarea', label: 'Description' },
    { name: 'applicationName', type: 'text', label: 'Application Name' },
    { name: 'authors', type: 'relationship', label: 'Authors', relationTo: 'users', hasMany: true },
    {
        name: 'generator',
        type: 'text',
        label: 'Generator',
        defaultValue: 'Shadcn UI Payload CMS Template',
        admin: { readOnly: true },
    },
    {
        name: 'keywords',
        type: 'relationship',
        label: 'Keywords',
        relationTo: 'tags',
        hasMany: true,
    },
    {
        name: 'referrer',
        type: 'select',
        label: 'Referrer',
        options: [
            'no-referrer',
            'origin',
            'no-referrer-when-downgrade',
            'origin-when-cross-origin',
            'same-origin',
            'strict-origin',
            'strict-origin-when-cross-origin',
        ],
    },
    {
        name: 'creator',
        type: 'text',
        label: 'Creator',
        defaultValue: 'Coffee Dev Team',
        admin: { readOnly: true },
    },
    {
        name: 'publisher',
        type: 'text',
        label: 'Publisher',
        defaultValue: 'Coffee Dev Pvt Ltd',
        admin: { readOnly: true },
    },
    { name: 'robots', type: 'text', label: 'Robots' },
    {
        name: 'alternates',
        type: 'group',
        label: 'Alternates',
        fields: [
            { name: 'canonical', type: 'text', label: 'Canonical' },
            {
                name: 'languages',
                label: 'Languages',
                labels: { singular: 'Language', plural: 'Languages' },
                type: 'array',
                fields: [
                    {
                        type: 'row',
                        fields: [
                            { name: 'language', type: 'text', label: 'Language' },
                            { name: 'url', type: 'text', label: 'Url' },
                        ],
                    },
                ],
            },
            {
                name: 'media',
                type: 'array',
                labels: { singular: 'Medium', plural: 'Media' },
                fields: [
                    {
                        type: 'row',
                        fields: [
                            { name: 'medium', type: 'text', label: 'Medium' },
                            { name: 'url', type: 'text', label: 'Url' },
                        ],
                    },
                ],
            },
            {
                name: 'types',
                type: 'array',
                labels: { singular: 'Type', plural: 'Types' },
                fields: [
                    {
                        type: 'row',
                        fields: [
                            { name: 'type', type: 'text', label: 'Type' },
                            { name: 'url', type: 'text', label: 'Url' },
                        ],
                    },
                ],
            },
        ],
    },
    { name: 'icons', type: 'upload', label: 'Icons', relationTo: 'media', hasMany: true },
    { name: 'manifest', type: 'text', label: 'Manifest' },
    {
        name: 'openGraph',
        type: 'blocks',
        label: 'Opengraph',
        labels: { singular: 'Opengraph Record', plural: 'Opengraph Records' },
        maxRows: 1,
        blocks: [
            {
                slug: 'OpenGraphWebsite',
                labels: { singular: 'Opengraph Website', plural: 'Opengraph Websites' },
                fields: [
                    {
                        name: 'type',
                        type: 'text',
                        defaultValue: 'website',
                        admin: { readOnly: true },
                    },
                    {
                        name: 'determiner',
                        label: 'Determiner',
                        type: 'select',
                        options: ['a', 'an', 'the', 'auto', ''],
                    },
                    {
                        name: 'title',
                        label: 'Title',
                        type: 'group',
                        fields: [
                            { name: 'default', type: 'text', label: 'Default' },
                            { name: 'template', type: 'text', label: 'Template' },
                            { name: 'absolute', type: 'text', label: 'Absolute' },
                        ],
                    },
                    { name: 'description', type: 'textarea', label: 'Description' },
                    {
                        name: 'emails',
                        type: 'array',
                        label: 'Emails',
                        labels: { singular: 'Email', plural: 'Emails' },
                        fields: [{ name: 'email', type: 'email', label: '' }],
                    },
                    {
                        name: 'phoneNumbers',
                        type: 'array',
                        label: 'Phone Numbers',
                        labels: { singular: 'Phone Number', plural: 'Phone Numbers' },
                        fields: [{ name: 'phone_number', type: 'text', label: '' }],
                    },
                    {
                        name: 'faxNumbers',
                        type: 'array',
                        label: 'Fax Numbers',
                        labels: { singular: 'Fax Number', plural: 'Fax Numbers' },
                        fields: [{ name: 'fax_number', type: 'text', label: '' }],
                    },
                    { name: 'siteName', type: 'text', label: 'Site Name' },
                    { name: 'locale', type: 'text', label: 'Locale' },
                    {
                        name: 'alternateLocale',
                        type: 'array',
                        label: 'Alternate Locales',
                        labels: { singular: 'Alternate Locale', plural: 'Alternate Locales' },
                        fields: [{ name: 'alternate_locale', type: 'text', label: '' }],
                    },
                    {
                        name: 'images',
                        type: 'upload',
                        label: 'Images',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'audio',
                        type: 'upload',
                        label: 'Audio',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'videos',
                        type: 'upload',
                        label: 'Videos',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    { name: 'url', type: 'text', label: 'Url' },
                    { name: 'countryName', type: 'text', label: 'Country Name' },
                    { name: 'ttl', type: 'number', label: 'Ttl' },
                ],
            },
            {
                slug: 'OpenGraphArticle',
                labels: { singular: 'Opengraph Article', plural: 'Opengraph Articles' },
                fields: [
                    {
                        name: 'type',
                        type: 'text',
                        defaultValue: 'article',
                        admin: { readOnly: true },
                    },
                    {
                        name: 'determiner',
                        label: 'Determiner',
                        type: 'select',
                        options: ['a', 'an', 'the', 'auto', ''],
                    },
                    {
                        name: 'title',
                        label: 'Title',
                        type: 'group',
                        fields: [
                            { name: 'default', type: 'text', label: 'Default' },
                            { name: 'template', type: 'text', label: 'Template' },
                            { name: 'absolute', type: 'text', label: 'Absolute' },
                        ],
                    },
                    { name: 'description', type: 'textarea', label: 'Description' },
                    {
                        name: 'emails',
                        type: 'array',
                        label: 'Emails',
                        labels: { singular: 'Email', plural: 'Emails' },
                        fields: [{ name: 'email', type: 'email', label: '' }],
                    },
                    {
                        name: 'phoneNumbers',
                        type: 'array',
                        label: 'Phone Numbers',
                        labels: { singular: 'Phone Number', plural: 'Phone Numbers' },
                        fields: [{ name: 'phone_number', type: 'text', label: '' }],
                    },
                    {
                        name: 'faxNumbers',
                        type: 'array',
                        label: 'Fax Numbers',
                        labels: { singular: 'Fax Number', plural: 'Fax Numbers' },
                        fields: [{ name: 'fax_number', type: 'text', label: '' }],
                    },
                    { name: 'siteName', type: 'text', label: 'Site Name' },
                    { name: 'locale', type: 'text', label: 'Locale' },
                    {
                        name: 'alternateLocale',
                        type: 'array',
                        label: 'Alternate Locales',
                        labels: { singular: 'Alternate Locale', plural: 'Alternate Locales' },
                        fields: [{ name: 'alternate_locale', type: 'text', label: '' }],
                    },
                    {
                        name: 'images',
                        type: 'upload',
                        label: 'Images',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'audio',
                        type: 'upload',
                        label: 'Audio',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'videos',
                        type: 'upload',
                        label: 'Videos',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    { name: 'url', type: 'text', label: 'Url' },
                    { name: 'countryName', type: 'text', label: 'Country Name' },
                    { name: 'ttl', type: 'number', label: 'Ttl' },
                    {
                        name: 'publishedTime',
                        type: 'date',
                        label: 'Published Time',
                        admin: { date: { pickerAppearance: 'dayAndTime' } },
                    },
                    {
                        name: 'modifiedTime',
                        type: 'date',
                        label: 'Modified Time',
                        admin: { date: { pickerAppearance: 'dayAndTime' } },
                    },
                    {
                        name: 'expirationTime',
                        type: 'date',
                        label: 'Expiration Time',
                        admin: { date: { pickerAppearance: 'dayAndTime' } },
                    },
                    {
                        name: 'authors',
                        type: 'relationship',
                        label: 'Authors',
                        relationTo: 'users',
                        hasMany: true,
                    },
                    { name: 'section', type: 'text', label: 'Section' },
                    {
                        name: 'tags',
                        type: 'relationship',
                        label: 'Tags',
                        relationTo: 'tags',
                        hasMany: true,
                    },
                ],
            },
            {
                slug: 'OpenGraphBook',
                labels: { singular: 'Opengraph Book', plural: 'Opengraph Books' },
                fields: [
                    {
                        name: 'type',
                        type: 'text',
                        defaultValue: 'book',
                        admin: { readOnly: true },
                    },
                    {
                        name: 'determiner',
                        label: 'Determiner',
                        type: 'select',
                        options: ['a', 'an', 'the', 'auto', ''],
                    },
                    {
                        name: 'title',
                        label: 'Title',
                        type: 'group',
                        fields: [
                            { name: 'default', type: 'text', label: 'Default' },
                            { name: 'template', type: 'text', label: 'Template' },
                            { name: 'absolute', type: 'text', label: 'Absolute' },
                        ],
                    },
                    { name: 'description', type: 'textarea', label: 'Description' },
                    {
                        name: 'emails',
                        type: 'array',
                        label: 'Emails',
                        labels: { singular: 'Email', plural: 'Emails' },
                        fields: [{ name: 'email', type: 'email', label: '' }],
                    },
                    {
                        name: 'phoneNumbers',
                        type: 'array',
                        label: 'Phone Numbers',
                        labels: { singular: 'Phone Number', plural: 'Phone Numbers' },
                        fields: [{ name: 'phone_number', type: 'text', label: '' }],
                    },
                    {
                        name: 'faxNumbers',
                        type: 'array',
                        label: 'Fax Numbers',
                        labels: { singular: 'Fax Number', plural: 'Fax Numbers' },
                        fields: [{ name: 'fax_number', type: 'text', label: '' }],
                    },
                    { name: 'siteName', type: 'text', label: 'Site Name' },
                    { name: 'locale', type: 'text', label: 'Locale' },
                    {
                        name: 'alternateLocale',
                        type: 'array',
                        label: 'Alternate Locales',
                        labels: { singular: 'Alternate Locale', plural: 'Alternate Locales' },
                        fields: [{ name: 'alternate_locale', type: 'text', label: '' }],
                    },
                    {
                        name: 'images',
                        type: 'upload',
                        label: 'Images',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'audio',
                        type: 'upload',
                        label: 'Audio',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'videos',
                        type: 'upload',
                        label: 'Videos',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    { name: 'url', type: 'text', label: 'Url' },
                    { name: 'countryName', type: 'text', label: 'Country Name' },
                    { name: 'ttl', type: 'number', label: 'Ttl' },
                    { name: 'isbn', type: 'number', label: 'Isbn' },
                    {
                        name: 'releaseDate',
                        type: 'date',
                        label: 'Release Time',
                        admin: { date: { pickerAppearance: 'dayAndTime' } },
                    },
                    {
                        name: 'authors',
                        type: 'relationship',
                        label: 'Authors',
                        relationTo: 'users',
                        hasMany: true,
                    },
                    {
                        name: 'tags',
                        type: 'relationship',
                        label: 'Tags',
                        relationTo: 'tags',
                        hasMany: true,
                    },
                ],
            },
            {
                slug: 'OpenGraphProfile',
                labels: { singular: 'Opengraph Profile', plural: 'Opengraph Profiles' },
                fields: [
                    {
                        name: 'type',
                        type: 'text',
                        defaultValue: 'profile',
                        admin: { readOnly: true },
                    },
                    {
                        name: 'determiner',
                        label: 'Determiner',
                        type: 'select',
                        options: ['a', 'an', 'the', 'auto', ''],
                    },
                    {
                        name: 'title',
                        label: 'Title',
                        type: 'group',
                        fields: [
                            { name: 'default', type: 'text', label: 'Default' },
                            { name: 'template', type: 'text', label: 'Template' },
                            { name: 'absolute', type: 'text', label: 'Absolute' },
                        ],
                    },
                    { name: 'description', type: 'textarea', label: 'Description' },
                    {
                        name: 'emails',
                        type: 'array',
                        label: 'Emails',
                        labels: { singular: 'Email', plural: 'Emails' },
                        fields: [{ name: 'email', type: 'email', label: '' }],
                    },
                    {
                        name: 'phoneNumbers',
                        type: 'array',
                        label: 'Phone Numbers',
                        labels: { singular: 'Phone Number', plural: 'Phone Numbers' },
                        fields: [{ name: 'phone_number', type: 'text', label: '' }],
                    },
                    {
                        name: 'faxNumbers',
                        type: 'array',
                        label: 'Fax Numbers',
                        labels: { singular: 'Fax Number', plural: 'Fax Numbers' },
                        fields: [{ name: 'fax_number', type: 'text', label: '' }],
                    },
                    { name: 'siteName', type: 'text', label: 'Site Name' },
                    { name: 'locale', type: 'text', label: 'Locale' },
                    {
                        name: 'alternateLocale',
                        type: 'array',
                        label: 'Alternate Locales',
                        labels: { singular: 'Alternate Locale', plural: 'Alternate Locales' },
                        fields: [{ name: 'alternate_locale', type: 'text', label: '' }],
                    },
                    {
                        name: 'images',
                        type: 'upload',
                        label: 'Images',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'audio',
                        type: 'upload',
                        label: 'Audio',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'videos',
                        type: 'upload',
                        label: 'Videos',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    { name: 'url', type: 'text', label: 'Url' },
                    { name: 'countryName', type: 'text', label: 'Country Name' },
                    { name: 'ttl', type: 'number', label: 'Ttl' },
                    { name: 'firstName', type: 'text', label: 'First Name' },
                    { name: 'lastName', type: 'text', label: 'Last Name' },
                    { name: 'username', type: 'text', label: 'User Name' },
                    {
                        name: 'gender',
                        type: 'select',
                        label: 'Gender',
                        options: ['male', 'female'],
                    },
                ],
            },
            {
                slug: 'OpenGraphMusicSong',
                labels: { singular: 'Opengraph Music Song', plural: 'Opengraph Music Songs' },
                fields: [
                    {
                        name: 'type',
                        type: 'text',
                        defaultValue: 'music.song',
                        admin: { readOnly: true },
                    },
                    {
                        name: 'determiner',
                        label: 'Determiner',
                        type: 'select',
                        options: ['a', 'an', 'the', 'auto', ''],
                    },
                    {
                        name: 'title',
                        label: 'Title',
                        type: 'group',
                        fields: [
                            { name: 'default', type: 'text', label: 'Default' },
                            { name: 'template', type: 'text', label: 'Template' },
                            { name: 'absolute', type: 'text', label: 'Absolute' },
                        ],
                    },
                    { name: 'description', type: 'textarea', label: 'Description' },
                    {
                        name: 'emails',
                        type: 'array',
                        label: 'Emails',
                        labels: { singular: 'Email', plural: 'Emails' },
                        fields: [{ name: 'email', type: 'email', label: '' }],
                    },
                    {
                        name: 'phoneNumbers',
                        type: 'array',
                        label: 'Phone Numbers',
                        labels: { singular: 'Phone Number', plural: 'Phone Numbers' },
                        fields: [{ name: 'phone_number', type: 'text', label: '' }],
                    },
                    {
                        name: 'faxNumbers',
                        type: 'array',
                        label: 'Fax Numbers',
                        labels: { singular: 'Fax Number', plural: 'Fax Numbers' },
                        fields: [{ name: 'fax_number', type: 'text', label: '' }],
                    },
                    { name: 'siteName', type: 'text', label: 'Site Name' },
                    { name: 'locale', type: 'text', label: 'Locale' },
                    {
                        name: 'alternateLocale',
                        type: 'array',
                        label: 'Alternate Locales',
                        labels: { singular: 'Alternate Locale', plural: 'Alternate Locales' },
                        fields: [{ name: 'alternate_locale', type: 'text', label: '' }],
                    },
                    {
                        name: 'images',
                        type: 'upload',
                        label: 'Images',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'audio',
                        type: 'upload',
                        label: 'Audio',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'videos',
                        type: 'upload',
                        label: 'Videos',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    { name: 'url', type: 'text', label: 'Url' },
                    { name: 'countryName', type: 'text', label: 'Country Name' },
                    { name: 'ttl', type: 'number', label: 'Ttl' },
                    { name: 'duration', type: 'number', label: 'Duration' },
                    {
                        name: 'albums',
                        type: 'array',
                        label: 'Albums',
                        labels: { singular: 'Album', plural: 'Albums' },
                        fields: [{ name: 'album', type: 'text', label: '' }],
                    },
                    {
                        name: 'musicians',
                        type: 'array',
                        label: 'Musicians',
                        labels: { singular: 'Musician', plural: 'Musicians' },
                        fields: [{ name: 'musician', type: 'text', label: '' }],
                    },
                ],
            },
            {
                slug: 'OpenGraphMusicAlbum',
                labels: { singular: 'Opengraph Music Album', plural: 'Opengraph Music Albums' },
                fields: [
                    {
                        name: 'type',
                        type: 'text',
                        defaultValue: 'music.album',
                        admin: { readOnly: true },
                    },
                    {
                        name: 'determiner',
                        label: 'Determiner',
                        type: 'select',
                        options: ['a', 'an', 'the', 'auto', ''],
                    },
                    {
                        name: 'title',
                        label: 'Title',
                        type: 'group',
                        fields: [
                            { name: 'default', type: 'text', label: 'Default' },
                            { name: 'template', type: 'text', label: 'Template' },
                            { name: 'absolute', type: 'text', label: 'Absolute' },
                        ],
                    },
                    { name: 'description', type: 'textarea', label: 'Description' },
                    {
                        name: 'emails',
                        type: 'array',
                        label: 'Emails',
                        labels: { singular: 'Email', plural: 'Emails' },
                        fields: [{ name: 'email', type: 'email', label: '' }],
                    },
                    {
                        name: 'phoneNumbers',
                        type: 'array',
                        label: 'Phone Numbers',
                        labels: { singular: 'Phone Number', plural: 'Phone Numbers' },
                        fields: [{ name: 'phone_number', type: 'text', label: '' }],
                    },
                    {
                        name: 'faxNumbers',
                        type: 'array',
                        label: 'Fax Numbers',
                        labels: { singular: 'Fax Number', plural: 'Fax Numbers' },
                        fields: [{ name: 'fax_number', type: 'text', label: '' }],
                    },
                    { name: 'siteName', type: 'text', label: 'Site Name' },
                    { name: 'locale', type: 'text', label: 'Locale' },
                    {
                        name: 'alternateLocale',
                        type: 'array',
                        label: 'Alternate Locales',
                        labels: { singular: 'Alternate Locale', plural: 'Alternate Locales' },
                        fields: [{ name: 'alternate_locale', type: 'text', label: '' }],
                    },
                    {
                        name: 'images',
                        type: 'upload',
                        label: 'Images',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'audio',
                        type: 'upload',
                        label: 'Audio',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'videos',
                        type: 'upload',
                        label: 'Videos',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    { name: 'url', type: 'text', label: 'Url' },
                    { name: 'countryName', type: 'text', label: 'Country Name' },
                    { name: 'ttl', type: 'number', label: 'Ttl' },
                    {
                        name: 'songs',
                        type: 'array',
                        label: 'Songs',
                        labels: { singular: 'Song', plural: 'Songs' },
                        fields: [{ name: 'song', type: 'text', label: '' }],
                    },
                    {
                        name: 'musicians',
                        type: 'array',
                        label: 'Musicians',
                        labels: { singular: 'Musician', plural: 'Musicians' },
                        fields: [{ name: 'musician', type: 'text', label: '' }],
                    },
                    {
                        name: 'releaseDate',
                        type: 'date',
                        label: 'Release Date',
                        admin: { date: { pickerAppearance: 'dayAndTime' } },
                    },
                ],
            },
            {
                slug: 'OpenGraphMusicPlaylist',
                labels: {
                    singular: 'Opengraph Music Playlist',
                    plural: 'Opengraph Music Playlists',
                },
                fields: [
                    {
                        name: 'type',
                        type: 'text',
                        defaultValue: 'music.playlist',
                        admin: { readOnly: true },
                    },
                    {
                        name: 'determiner',
                        label: 'Determiner',
                        type: 'select',
                        options: ['a', 'an', 'the', 'auto', ''],
                    },
                    {
                        name: 'title',
                        label: 'Title',
                        type: 'group',
                        fields: [
                            { name: 'default', type: 'text', label: 'Default' },
                            { name: 'template', type: 'text', label: 'Template' },
                            { name: 'absolute', type: 'text', label: 'Absolute' },
                        ],
                    },
                    { name: 'description', type: 'textarea', label: 'Description' },
                    {
                        name: 'emails',
                        type: 'array',
                        label: 'Emails',
                        labels: { singular: 'Email', plural: 'Emails' },
                        fields: [{ name: 'email', type: 'email', label: '' }],
                    },
                    {
                        name: 'phoneNumbers',
                        type: 'array',
                        label: 'Phone Numbers',
                        labels: { singular: 'Phone Number', plural: 'Phone Numbers' },
                        fields: [{ name: 'phone_number', type: 'text', label: '' }],
                    },
                    {
                        name: 'faxNumbers',
                        type: 'array',
                        label: 'Fax Numbers',
                        labels: { singular: 'Fax Number', plural: 'Fax Numbers' },
                        fields: [{ name: 'fax_number', type: 'text', label: '' }],
                    },
                    { name: 'siteName', type: 'text', label: 'Site Name' },
                    { name: 'locale', type: 'text', label: 'Locale' },
                    {
                        name: 'alternateLocale',
                        type: 'array',
                        label: 'Alternate Locales',
                        labels: { singular: 'Alternate Locale', plural: 'Alternate Locales' },
                        fields: [{ name: 'alternate_locale', type: 'text', label: '' }],
                    },
                    {
                        name: 'images',
                        type: 'upload',
                        label: 'Images',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'audio',
                        type: 'upload',
                        label: 'Audio',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'videos',
                        type: 'upload',
                        label: 'Videos',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    { name: 'url', type: 'text', label: 'Url' },
                    { name: 'countryName', type: 'text', label: 'Country Name' },
                    { name: 'ttl', type: 'number', label: 'Ttl' },
                    {
                        name: 'songs',
                        type: 'array',
                        label: 'Songs',
                        labels: { singular: 'Song', plural: 'Songs' },
                        fields: [{ name: 'song', type: 'text', label: '' }],
                    },
                    {
                        name: 'creators',
                        type: 'array',
                        label: 'Creators',
                        labels: { singular: 'Creator', plural: 'Creators' },
                        fields: [{ name: 'creator', type: 'text', label: '' }],
                    },
                ],
            },
            {
                slug: 'OpenGraphRadioStation',
                labels: { singular: 'Opengraph Radio Station', plural: 'Opengraph Radio Stations' },
                fields: [
                    {
                        name: 'type',
                        type: 'text',
                        defaultValue: 'music.radio_station',
                        admin: { readOnly: true },
                    },
                    {
                        name: 'determiner',
                        label: 'Determiner',
                        type: 'select',
                        options: ['a', 'an', 'the', 'auto', ''],
                    },
                    {
                        name: 'title',
                        label: 'Title',
                        type: 'group',
                        fields: [
                            { name: 'default', type: 'text', label: 'Default' },
                            { name: 'template', type: 'text', label: 'Template' },
                            { name: 'absolute', type: 'text', label: 'Absolute' },
                        ],
                    },
                    { name: 'description', type: 'textarea', label: 'Description' },
                    {
                        name: 'emails',
                        type: 'array',
                        label: 'Emails',
                        labels: { singular: 'Email', plural: 'Emails' },
                        fields: [{ name: 'email', type: 'email', label: '' }],
                    },
                    {
                        name: 'phoneNumbers',
                        type: 'array',
                        label: 'Phone Numbers',
                        labels: { singular: 'Phone Number', plural: 'Phone Numbers' },
                        fields: [{ name: 'phone_number', type: 'text', label: '' }],
                    },
                    {
                        name: 'faxNumbers',
                        type: 'array',
                        label: 'Fax Numbers',
                        labels: { singular: 'Fax Number', plural: 'Fax Numbers' },
                        fields: [{ name: 'fax_number', type: 'text', label: '' }],
                    },
                    { name: 'siteName', type: 'text', label: 'Site Name' },
                    { name: 'locale', type: 'text', label: 'Locale' },
                    {
                        name: 'alternateLocale',
                        type: 'array',
                        label: 'Alternate Locales',
                        labels: { singular: 'Alternate Locale', plural: 'Alternate Locales' },
                        fields: [{ name: 'alternate_locale', type: 'text', label: '' }],
                    },
                    {
                        name: 'images',
                        type: 'upload',
                        label: 'Images',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'audio',
                        type: 'upload',
                        label: 'Audio',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'videos',
                        type: 'upload',
                        label: 'Videos',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    { name: 'url', type: 'text', label: 'Url' },
                    { name: 'countryName', type: 'text', label: 'Country Name' },
                    { name: 'ttl', type: 'number', label: 'Ttl' },
                    {
                        name: 'creators',
                        type: 'array',
                        label: 'Creators',
                        labels: { singular: 'Creator', plural: 'Creators' },
                        fields: [{ name: 'creator', type: 'text', label: '' }],
                    },
                ],
            },
            {
                slug: 'OpenGraphVideoMovie',
                labels: { singular: 'Opengraph Video Movie', plural: 'Opengraph Video Movies' },
                fields: [
                    {
                        name: 'type',
                        type: 'text',
                        defaultValue: 'video.movie',
                        admin: { readOnly: true },
                    },
                    {
                        name: 'determiner',
                        label: 'Determiner',
                        type: 'select',
                        options: ['a', 'an', 'the', 'auto', ''],
                    },
                    {
                        name: 'title',
                        label: 'Title',
                        type: 'group',
                        fields: [
                            { name: 'default', type: 'text', label: 'Default' },
                            { name: 'template', type: 'text', label: 'Template' },
                            { name: 'absolute', type: 'text', label: 'Absolute' },
                        ],
                    },
                    { name: 'description', type: 'textarea', label: 'Description' },
                    {
                        name: 'emails',
                        type: 'array',
                        label: 'Emails',
                        labels: { singular: 'Email', plural: 'Emails' },
                        fields: [{ name: 'email', type: 'email', label: '' }],
                    },
                    {
                        name: 'phoneNumbers',
                        type: 'array',
                        label: 'Phone Numbers',
                        labels: { singular: 'Phone Number', plural: 'Phone Numbers' },
                        fields: [{ name: 'phone_number', type: 'text', label: '' }],
                    },
                    {
                        name: 'faxNumbers',
                        type: 'array',
                        label: 'Fax Numbers',
                        labels: { singular: 'Fax Number', plural: 'Fax Numbers' },
                        fields: [{ name: 'fax_number', type: 'text', label: '' }],
                    },
                    { name: 'siteName', type: 'text', label: 'Site Name' },
                    { name: 'locale', type: 'text', label: 'Locale' },
                    {
                        name: 'alternateLocale',
                        type: 'array',
                        label: 'Alternate Locales',
                        labels: { singular: 'Alternate Locale', plural: 'Alternate Locales' },
                        fields: [{ name: 'alternate_locale', type: 'text', label: '' }],
                    },
                    {
                        name: 'images',
                        type: 'upload',
                        label: 'Images',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'audio',
                        type: 'upload',
                        label: 'Audio',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'videos',
                        type: 'upload',
                        label: 'Videos',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    { name: 'url', type: 'text', label: 'Url' },
                    { name: 'countryName', type: 'text', label: 'Country Name' },
                    { name: 'ttl', type: 'number', label: 'Ttl' },
                    {
                        name: 'actors',
                        type: 'array',
                        label: 'Actors',
                        labels: { singular: 'Actor', plural: 'Actors' },
                        fields: [{ name: 'actor', type: 'text', label: '' }],
                    },
                    {
                        name: 'directors',
                        type: 'array',
                        label: 'Directors',
                        labels: { singular: 'Director', plural: 'Directors' },
                        fields: [{ name: 'director', type: 'text', label: '' }],
                    },
                    {
                        name: 'writers',
                        type: 'array',
                        label: 'Writers',
                        labels: { singular: 'Writer', plural: 'Writers' },
                        fields: [{ name: 'writer', type: 'text', label: '' }],
                    },
                    { name: 'duration', type: 'number', label: 'Duration' },
                    {
                        name: 'releaseDate',
                        type: 'date',
                        label: 'Release Date',
                        admin: { date: { pickerAppearance: 'dayAndTime' } },
                    },
                    {
                        name: 'tags',
                        type: 'relationship',
                        label: 'Tags',
                        relationTo: 'tags',
                        hasMany: true,
                    },
                ],
            },
            {
                slug: 'OpenGraphVideoEpisode',
                labels: { singular: 'Opengraph Video Episode', plural: 'Opengraph Video Episodes' },
                fields: [
                    {
                        name: 'type',
                        type: 'text',
                        defaultValue: 'video.episode',
                        admin: { readOnly: true },
                    },
                    {
                        name: 'determiner',
                        label: 'Determiner',
                        type: 'select',
                        options: ['a', 'an', 'the', 'auto', ''],
                    },
                    {
                        name: 'title',
                        label: 'Title',
                        type: 'group',
                        fields: [
                            { name: 'default', type: 'text', label: 'Default' },
                            { name: 'template', type: 'text', label: 'Template' },
                            { name: 'absolute', type: 'text', label: 'Absolute' },
                        ],
                    },
                    { name: 'description', type: 'textarea', label: 'Description' },
                    {
                        name: 'emails',
                        type: 'array',
                        label: 'Emails',
                        labels: { singular: 'Email', plural: 'Emails' },
                        fields: [{ name: 'email', type: 'email', label: '' }],
                    },
                    {
                        name: 'phoneNumbers',
                        type: 'array',
                        label: 'Phone Numbers',
                        labels: { singular: 'Phone Number', plural: 'Phone Numbers' },
                        fields: [{ name: 'phone_number', type: 'text', label: '' }],
                    },
                    {
                        name: 'faxNumbers',
                        type: 'array',
                        label: 'Fax Numbers',
                        labels: { singular: 'Fax Number', plural: 'Fax Numbers' },
                        fields: [{ name: 'fax_number', type: 'text', label: '' }],
                    },
                    { name: 'siteName', type: 'text', label: 'Site Name' },
                    { name: 'locale', type: 'text', label: 'Locale' },
                    {
                        name: 'alternateLocale',
                        type: 'array',
                        label: 'Alternate Locales',
                        labels: { singular: 'Alternate Locale', plural: 'Alternate Locales' },
                        fields: [{ name: 'alternate_locale', type: 'text', label: '' }],
                    },
                    {
                        name: 'images',
                        type: 'upload',
                        label: 'Images',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'audio',
                        type: 'upload',
                        label: 'Audio',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'videos',
                        type: 'upload',
                        label: 'Videos',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    { name: 'url', type: 'text', label: 'Url' },
                    { name: 'countryName', type: 'text', label: 'Country Name' },
                    { name: 'ttl', type: 'number', label: 'Ttl' },
                    {
                        name: 'actors',
                        type: 'array',
                        label: 'Actors',
                        labels: { singular: 'Actor', plural: 'Actors' },
                        fields: [{ name: 'actor', type: 'text', label: '' }],
                    },
                    {
                        name: 'directors',
                        type: 'array',
                        label: 'Directors',
                        labels: { singular: 'Director', plural: 'Directors' },
                        fields: [{ name: 'director', type: 'text', label: '' }],
                    },
                    {
                        name: 'writers',
                        type: 'array',
                        label: 'Writers',
                        labels: { singular: 'Writer', plural: 'Writers' },
                        fields: [{ name: 'writer', type: 'text', label: '' }],
                    },
                    { name: 'duration', type: 'number', label: 'Duration' },
                    {
                        name: 'releaseDate',
                        type: 'date',
                        label: 'Release Date',
                        admin: { date: { pickerAppearance: 'dayAndTime' } },
                    },
                    {
                        name: 'tags',
                        type: 'relationship',
                        label: 'Tags',
                        relationTo: 'tags',
                        hasMany: true,
                    },
                    { name: 'series', type: 'text', label: 'Series' },
                ],
            },
            {
                slug: 'OpenGraphVideoTVShow',
                labels: { singular: 'Opengraph Video TV Show', plural: 'Opengraph Video TV Shows' },
                fields: [
                    {
                        name: 'type',
                        type: 'text',
                        defaultValue: 'video.tv_show',
                        admin: { readOnly: true },
                    },
                    {
                        name: 'determiner',
                        label: 'Determiner',
                        type: 'select',
                        options: ['a', 'an', 'the', 'auto', ''],
                    },
                    {
                        name: 'title',
                        label: 'Title',
                        type: 'group',
                        fields: [
                            { name: 'default', type: 'text', label: 'Default' },
                            { name: 'template', type: 'text', label: 'Template' },
                            { name: 'absolute', type: 'text', label: 'Absolute' },
                        ],
                    },
                    { name: 'description', type: 'textarea', label: 'Description' },
                    {
                        name: 'emails',
                        type: 'array',
                        label: 'Emails',
                        labels: { singular: 'Email', plural: 'Emails' },
                        fields: [{ name: 'email', type: 'email', label: '' }],
                    },
                    {
                        name: 'phoneNumbers',
                        type: 'array',
                        label: 'Phone Numbers',
                        labels: { singular: 'Phone Number', plural: 'Phone Numbers' },
                        fields: [{ name: 'phone_number', type: 'text', label: '' }],
                    },
                    {
                        name: 'faxNumbers',
                        type: 'array',
                        label: 'Fax Numbers',
                        labels: { singular: 'Fax Number', plural: 'Fax Numbers' },
                        fields: [{ name: 'fax_number', type: 'text', label: '' }],
                    },
                    { name: 'siteName', type: 'text', label: 'Site Name' },
                    { name: 'locale', type: 'text', label: 'Locale' },
                    {
                        name: 'alternateLocale',
                        type: 'array',
                        label: 'Alternate Locales',
                        labels: { singular: 'Alternate Locale', plural: 'Alternate Locales' },
                        fields: [{ name: 'alternate_locale', type: 'text', label: '' }],
                    },
                    {
                        name: 'images',
                        type: 'upload',
                        label: 'Images',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'audio',
                        type: 'upload',
                        label: 'Audio',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'videos',
                        type: 'upload',
                        label: 'Videos',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    { name: 'url', type: 'text', label: 'Url' },
                    { name: 'countryName', type: 'text', label: 'Country Name' },
                    { name: 'ttl', type: 'number', label: 'Ttl' },
                ],
            },
            {
                slug: 'OpenGraphVideoOther',
                labels: { singular: 'Opengraph Video Other', plural: 'Opengraph Video Others' },
                fields: [
                    {
                        name: 'type',
                        type: 'text',
                        defaultValue: 'video.other',
                        admin: { readOnly: true },
                    },
                    {
                        name: 'determiner',
                        label: 'Determiner',
                        type: 'select',
                        options: ['a', 'an', 'the', 'auto', ''],
                    },
                    {
                        name: 'title',
                        label: 'Title',
                        type: 'group',
                        fields: [
                            { name: 'default', type: 'text', label: 'Default' },
                            { name: 'template', type: 'text', label: 'Template' },
                            { name: 'absolute', type: 'text', label: 'Absolute' },
                        ],
                    },
                    { name: 'description', type: 'textarea', label: 'Description' },
                    {
                        name: 'emails',
                        type: 'array',
                        label: 'Emails',
                        labels: { singular: 'Email', plural: 'Emails' },
                        fields: [{ name: 'email', type: 'email', label: '' }],
                    },
                    {
                        name: 'phoneNumbers',
                        type: 'array',
                        label: 'Phone Numbers',
                        labels: { singular: 'Phone Number', plural: 'Phone Numbers' },
                        fields: [{ name: 'phone_number', type: 'text', label: '' }],
                    },
                    {
                        name: 'faxNumbers',
                        type: 'array',
                        label: 'Fax Numbers',
                        labels: { singular: 'Fax Number', plural: 'Fax Numbers' },
                        fields: [{ name: 'fax_number', type: 'text', label: '' }],
                    },
                    { name: 'siteName', type: 'text', label: 'Site Name' },
                    { name: 'locale', type: 'text', label: 'Locale' },
                    {
                        name: 'alternateLocale',
                        type: 'array',
                        label: 'Alternate Locales',
                        labels: { singular: 'Alternate Locale', plural: 'Alternate Locales' },
                        fields: [{ name: 'alternate_locale', type: 'text', label: '' }],
                    },
                    {
                        name: 'images',
                        type: 'upload',
                        label: 'Images',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'audio',
                        type: 'upload',
                        label: 'Audio',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'videos',
                        type: 'upload',
                        label: 'Videos',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    { name: 'url', type: 'text', label: 'Url' },
                    { name: 'countryName', type: 'text', label: 'Country Name' },
                    { name: 'ttl', type: 'number', label: 'Ttl' },
                ],
            },
            {
                slug: 'OpenGraphMetadata',
                labels: { singular: 'Opengraph Metadata', plural: 'Opengraph Metadatas' },
                fields: [
                    {
                        name: 'determiner',
                        label: 'Determiner',
                        type: 'select',
                        options: ['a', 'an', 'the', 'auto', ''],
                    },
                    {
                        name: 'title',
                        label: 'Title',
                        type: 'group',
                        fields: [
                            { name: 'default', type: 'text', label: 'Default' },
                            { name: 'template', type: 'text', label: 'Template' },
                            { name: 'absolute', type: 'text', label: 'Absolute' },
                        ],
                    },
                    { name: 'description', type: 'textarea', label: 'Description' },
                    {
                        name: 'emails',
                        type: 'array',
                        label: 'Emails',
                        labels: { singular: 'Email', plural: 'Emails' },
                        fields: [{ name: 'email', type: 'email', label: '' }],
                    },
                    {
                        name: 'phoneNumbers',
                        type: 'array',
                        label: 'Phone Numbers',
                        labels: { singular: 'Phone Number', plural: 'Phone Numbers' },
                        fields: [{ name: 'phone_number', type: 'text', label: '' }],
                    },
                    {
                        name: 'faxNumbers',
                        type: 'array',
                        label: 'Fax Numbers',
                        labels: { singular: 'Fax Number', plural: 'Fax Numbers' },
                        fields: [{ name: 'fax_number', type: 'text', label: '' }],
                    },
                    { name: 'siteName', type: 'text', label: 'Site Name' },
                    { name: 'locale', type: 'text', label: 'Locale' },
                    {
                        name: 'alternateLocale',
                        type: 'array',
                        label: 'Alternate Locales',
                        labels: { singular: 'Alternate Locale', plural: 'Alternate Locales' },
                        fields: [{ name: 'alternate_locale', type: 'text', label: '' }],
                    },
                    {
                        name: 'images',
                        type: 'upload',
                        label: 'Images',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'audio',
                        type: 'upload',
                        label: 'Audio',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'videos',
                        type: 'upload',
                        label: 'Videos',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    { name: 'url', type: 'text', label: 'Url' },
                    { name: 'countryName', type: 'text', label: 'Country Name' },
                    { name: 'ttl', type: 'number', label: 'Ttl' },
                ],
            },
        ],
    },
    {
        name: 'twitter',
        type: 'blocks',
        label: 'Twitter',
        labels: { singular: 'Twitter Record', plural: 'Twitter Records' },
        maxRows: 1,
        blocks: [
            {
                slug: 'TwitterSummary',
                labels: { singular: 'Twitter Summary', plural: 'Twitter Summaries' },
                fields: [
                    {
                        name: 'card',
                        type: 'text',
                        label: 'Card',
                        defaultValue: 'summary',
                        admin: { readOnly: true },
                    },
                    { name: 'site', type: 'text', label: 'Site' },
                    { name: 'siteId', type: 'text', label: 'Site Id' },
                    {
                        name: 'creator',
                        type: 'text',
                        label: 'Creator',
                        defaultValue: 'Coffee Dev Team',
                        admin: { readOnly: true },
                    },
                    { name: 'creatorId', type: 'text', label: 'Creator Id' },
                    { name: 'description', type: 'textarea', label: 'Description' },
                    {
                        name: 'title',
                        type: 'group',
                        label: 'Title',
                        fields: [
                            { name: 'default', type: 'text', label: 'Default' },
                            { name: 'template', type: 'text', label: 'Template' },
                            { name: 'absolute', type: 'text', label: 'Absolute' },
                        ],
                    },
                    {
                        name: 'images',
                        type: 'upload',
                        label: 'Images',
                        relationTo: 'media',
                        hasMany: true,
                    },
                ],
            },
            {
                slug: 'TwitterSummaryLargeImage',
                labels: {
                    singular: 'Twitter Summary Large Image',
                    plural: 'Twitter Summary Large Images',
                },
                fields: [
                    {
                        name: 'card',
                        type: 'text',
                        label: 'Card',
                        defaultValue: 'summary_large_image',
                        admin: { readOnly: true },
                    },
                    { name: 'site', type: 'text', label: 'Site' },
                    { name: 'siteId', type: 'text', label: 'Site Id' },
                    {
                        name: 'creator',
                        type: 'text',
                        label: 'Creator',
                        defaultValue: 'Coffee Dev Team',
                        admin: { readOnly: true },
                    },
                    { name: 'creatorId', type: 'text', label: 'Creator Id' },
                    { name: 'description', type: 'textarea', label: 'Description' },
                    {
                        name: 'title',
                        type: 'group',
                        label: 'Title',
                        fields: [
                            { name: 'default', type: 'text', label: 'Default' },
                            { name: 'template', type: 'text', label: 'Template' },
                            { name: 'absolute', type: 'text', label: 'Absolute' },
                        ],
                    },
                    {
                        name: 'images',
                        type: 'upload',
                        label: 'Images',
                        relationTo: 'media',
                        hasMany: true,
                    },
                ],
            },
            {
                slug: 'TwitterPlayer',
                labels: { singular: 'Twitter Player', plural: 'Twitter Players' },
                fields: [
                    {
                        name: 'card',
                        type: 'text',
                        label: 'Card',
                        defaultValue: 'player',
                        admin: { readOnly: true },
                    },
                    { name: 'site', type: 'text', label: 'Site' },
                    { name: 'siteId', type: 'text', label: 'Site Id' },
                    {
                        name: 'creator',
                        type: 'text',
                        label: 'Creator',
                        defaultValue: 'Coffee Dev Team',
                        admin: { readOnly: true },
                    },
                    { name: 'creatorId', type: 'text', label: 'Creator Id' },
                    { name: 'description', type: 'textarea', label: 'Description' },
                    {
                        name: 'title',
                        type: 'group',
                        label: 'Title',
                        fields: [
                            { name: 'default', type: 'text', label: 'Default' },
                            { name: 'template', type: 'text', label: 'Template' },
                            { name: 'absolute', type: 'text', label: 'Absolute' },
                        ],
                    },
                    {
                        name: 'images',
                        type: 'upload',
                        label: 'Images',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'players',
                        type: 'array',
                        label: 'Players',
                        labels: { singular: 'Player', plural: 'Players' },
                        fields: [
                            { name: 'playerUrl', label: 'Player Url', type: 'text' },
                            { name: 'streamUrl', label: 'Stream Url', type: 'text' },
                            { name: 'width', label: 'Width', type: 'number' },
                            { name: 'height', label: 'Height', type: 'number' },
                        ],
                    },
                ],
            },
            {
                slug: 'TwitterApp',
                labels: { singular: 'Twitter App', plural: 'Twitter Apps' },
                fields: [
                    {
                        name: 'card',
                        type: 'text',
                        label: 'Card',
                        defaultValue: 'app',
                        admin: { readOnly: true },
                    },
                    { name: 'site', type: 'text', label: 'Site' },
                    { name: 'siteId', type: 'text', label: 'Site Id' },
                    {
                        name: 'creator',
                        type: 'text',
                        label: 'Creator',
                        defaultValue: 'Coffee Dev Team',
                        admin: { readOnly: true },
                    },
                    { name: 'creatorId', type: 'text', label: 'Creator Id' },
                    { name: 'description', type: 'textarea', label: 'Description' },
                    {
                        name: 'title',
                        type: 'group',
                        label: 'Title',
                        fields: [
                            { name: 'default', type: 'text', label: 'Default' },
                            { name: 'template', type: 'text', label: 'Template' },
                            { name: 'absolute', type: 'text', label: 'Absolute' },
                        ],
                    },
                    {
                        name: 'images',
                        type: 'upload',
                        label: 'Images',
                        relationTo: 'media',
                        hasMany: true,
                    },
                    {
                        name: 'app',
                        type: 'group',
                        label: 'App',
                        fields: [
                            {
                                name: 'id',
                                type: 'group',
                                label: 'Id',
                                fields: [
                                    { name: 'iphone', type: 'text', label: 'I Phone' },
                                    { name: 'ipad', type: 'text', label: 'I Pad' },
                                    { name: 'googleplay', type: 'text', label: 'Google Play' },
                                ],
                            },
                            {
                                name: 'url',
                                type: 'group',
                                label: 'Url',
                                fields: [
                                    { name: 'iphone', type: 'text', label: 'I Phone' },
                                    { name: 'ipad', type: 'text', label: 'I Pad' },
                                    { name: 'googleplay', type: 'text', label: 'Google Play' },
                                ],
                            },
                            { name: 'name', type: 'text', label: 'Name' },
                        ],
                    },
                ],
            },
            {
                slug: 'TwitterMetadata',
                labels: { singular: 'Twitter Metadata', plural: 'Twitter Metadatas' },
                fields: [
                    { name: 'site', type: 'text', label: 'Site' },
                    { name: 'siteId', type: 'text', label: 'Site Id' },
                    {
                        name: 'creator',
                        type: 'text',
                        label: 'Creator',
                        defaultValue: 'Coffee Dev Team',
                        admin: { readOnly: true },
                    },
                    { name: 'creatorId', type: 'text', label: 'Creator Id' },
                    { name: 'description', type: 'textarea', label: 'Description' },
                    {
                        name: 'title',
                        type: 'group',
                        label: 'Title',
                        fields: [
                            { name: 'default', type: 'text', label: 'Default' },
                            { name: 'template', type: 'text', label: 'Template' },
                            { name: 'absolute', type: 'text', label: 'Absolute' },
                        ],
                    },
                    {
                        name: 'images',
                        type: 'upload',
                        label: 'Images',
                        relationTo: 'media',
                        hasMany: true,
                    },
                ],
            },
        ],
    },
    {
        name: 'facebook',
        type: 'group',
        label: 'Facebook',
        fields: [
            { name: 'appId', label: 'App Id', type: 'text' },
            {
                name: 'admins',
                label: 'Admins',
                labels: { singular: 'Admin', plural: 'Admins' },
                type: 'array',
                fields: [{ name: 'admin', label: '', type: 'text' }],
            },
        ],
    },
    {
        name: 'pinterest',
        type: 'group',
        label: 'Pinterest',
        fields: [{ name: 'richPin', label: 'Rich Pin', type: 'text' }],
    },
    {
        name: 'verification',
        type: 'group',
        label: 'Verification',
        fields: [
            {
                name: 'google',
                label: 'Google',
                labels: { singular: 'Google', plural: 'Googles' },
                type: 'array',
                fields: [{ name: 'value', label: '', type: 'text' }],
            },
            {
                name: 'yahoo',
                label: 'Yahoo',
                labels: { singular: 'Yahoo', plural: 'Yahoos' },
                type: 'array',
                fields: [{ name: 'value', label: '', type: 'text' }],
            },
            {
                name: 'yandex',
                label: 'Yandex',
                labels: { singular: 'Yandex', plural: 'Yandexs' },
                type: 'array',
                fields: [{ name: 'value', label: '', type: 'text' }],
            },
            {
                name: 'me',
                label: 'Me',
                labels: { singular: 'Me', plural: 'Mes' },
                type: 'array',
                fields: [{ name: 'value', label: '', type: 'text' }],
            },
            {
                name: 'other',
                label: 'Other',
                labels: { singular: 'Other', plural: 'Others' },
                type: 'array',
                fields: [{ name: 'value', label: '', type: 'text' }],
            },
        ],
    },
    {
        name: 'appleWebApp',
        type: 'group',
        label: 'Apple Web App',
        fields: [
            { name: 'capable', label: 'Capable', type: 'checkbox' },
            { name: 'title', label: 'Title', type: 'text' },
            {
                name: 'startupImage',
                label: 'Startup Image',
                type: 'upload',
                relationTo: 'media',
                hasMany: true,
            },
            {
                name: 'statusBarStyle',
                label: 'Statusbar Style',
                type: 'select',
                options: ['default', 'black', 'black-translucent'],
            },
        ],
    },
    {
        name: 'formatDetection',
        label: 'Format Detection',
        type: 'group',
        fields: [
            { name: 'telephone', label: 'Telephone', type: 'checkbox' },
            { name: 'date', label: 'Date', type: 'checkbox' },
            { name: 'address', label: 'Address', type: 'checkbox' },
            { name: 'email', label: 'Email', type: 'checkbox' },
            { name: 'url', label: 'Url', type: 'checkbox' },
        ],
    },
    {
        name: 'itunes',
        type: 'group',
        label: 'Itunes',
        fields: [
            { name: 'appId', label: 'App Id', type: 'text' },
            { name: 'appArgument', label: 'App Argument', type: 'text' },
        ],
    },
    { name: 'abstract', label: 'Abstract', type: 'text' },
    {
        name: 'appLinks',
        label: 'App Links',
        type: 'group',
        fields: [
            {
                name: 'ios',
                label: 'Ios',
                type: 'array',
                fields: [
                    { name: 'url', label: 'Url', type: 'text' },
                    { name: 'app_store_id', label: 'Apple Store Id', type: 'text' },
                    { name: 'app_name', label: 'App Name', type: 'text' },
                ],
            },
            {
                name: 'iphone',
                label: 'Iphone',
                type: 'array',
                fields: [
                    { name: 'url', label: 'Url', type: 'text' },
                    { name: 'app_store_id', label: 'Apple Store Id', type: 'text' },
                    { name: 'app_name', label: 'App Name', type: 'text' },
                ],
            },
            {
                name: 'ipad',
                label: 'Ipad',
                type: 'array',
                fields: [
                    { name: 'url', label: 'Url', type: 'text' },
                    { name: 'app_store_id', label: 'Apple Store Id', type: 'text' },
                    { name: 'app_name', label: 'App Name', type: 'text' },
                ],
            },
            {
                name: 'android',
                label: 'Android',
                type: 'array',
                fields: [
                    { name: 'package', label: 'Package', type: 'text' },
                    { name: 'url', label: 'Url', type: 'text' },
                    { name: 'class', label: 'Class', type: 'text' },
                    { name: 'app_name', label: 'App Name', type: 'text' },
                ],
            },
            {
                name: 'windows_phone',
                label: 'Windows Phone',
                type: 'array',
                fields: [
                    { name: 'url', label: 'Url', type: 'text' },
                    { name: 'app_id', label: 'Apple Id', type: 'text' },
                    { name: 'app_name', label: 'App Name', type: 'text' },
                ],
            },
            {
                name: 'windows',
                label: 'Windows',
                type: 'array',
                fields: [
                    { name: 'url', label: 'Url', type: 'text' },
                    { name: 'app_id', label: 'Apple Id', type: 'text' },
                    { name: 'app_name', label: 'App Name', type: 'text' },
                ],
            },
            {
                name: 'windows_universal',
                label: 'Windows Universal',
                type: 'array',
                fields: [
                    { name: 'url', label: 'Url', type: 'text' },
                    { name: 'app_id', label: 'Apple Id', type: 'text' },
                    { name: 'app_name', label: 'App Name', type: 'text' },
                ],
            },
            {
                name: 'web',
                label: 'Web',
                type: 'array',
                fields: [
                    { name: 'url', label: 'Url', type: 'text' },
                    { name: 'should_fallback', label: 'Should Fallback', type: 'checkbox' },
                ],
            },
        ],
    },
    {
        name: 'archives',
        label: 'Archives',
        labels: { singular: 'Archive', plural: 'Archives' },
        type: 'array',
        fields: [{ name: 'archive', label: '', type: 'text' }],
    },
    {
        name: 'assets',
        label: 'Assets',
        labels: { singular: 'Asset', plural: 'Assets' },
        type: 'array',
        fields: [{ name: 'asset', label: '', type: 'text' }],
    },
    {
        name: 'bookmarks',
        label: 'Bookmarks',
        labels: { singular: 'Bookmark', plural: 'Bookmarks' },
        type: 'array',
        fields: [{ name: 'bookmark', label: '', type: 'text' }],
    },
    {
        name: 'pagination',
        label: 'Pagination',
        type: 'group',
        fields: [
            { name: 'previous', label: 'Previous', type: 'text' },
            { name: 'next', label: 'Next', type: 'text' },
        ],
    },
    { name: 'category', label: 'Category', type: 'text' },
    { name: 'classification', label: 'Classification', type: 'text' },
    { name: 'other', label: 'Other', type: 'json' },
]
