/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tags: Tag;
    categories: Category;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    metadata: Metadatum;
    robots: Robot;
    manifest: Manifest;
    sitemap: Sitemap;
  };
  globalsSelect: {
    metadata: MetadataSelect<false> | MetadataSelect<true>;
    robots: RobotsSelect<false> | RobotsSelect<true>;
    manifest: ManifestSelect<false> | ManifestSelect<true>;
    sitemap: SitemapSelect<false> | SitemapSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  picture?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  picture?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metadata".
 */
export interface Metadatum {
  id: number;
  metadataBase?: string | null;
  title?: {
    default?: string | null;
    template?: string | null;
    absolute?: string | null;
  };
  description?: string | null;
  applicationName?: string | null;
  authors?: (number | User)[] | null;
  generator?: string | null;
  keywords?: (number | Tag)[] | null;
  referrer?:
    | (
        | 'no-referrer'
        | 'origin'
        | 'no-referrer-when-downgrade'
        | 'origin-when-cross-origin'
        | 'same-origin'
        | 'strict-origin'
        | 'strict-origin-when-cross-origin'
      )
    | null;
  creator?: string | null;
  publisher?: string | null;
  robots?: string | null;
  alternates?: {
    canonical?: string | null;
    languages?:
      | {
          language?: string | null;
          url?: string | null;
          id?: string | null;
        }[]
      | null;
    media?:
      | {
          medium?: string | null;
          url?: string | null;
          id?: string | null;
        }[]
      | null;
    types?:
      | {
          type?: string | null;
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  icons?: (number | Media)[] | null;
  manifest?: string | null;
  openGraph?:
    | (
        | {
            type?: string | null;
            determiner?: ('a' | 'an' | 'the' | 'auto' | '') | null;
            title?: {
              default?: string | null;
              template?: string | null;
              absolute?: string | null;
            };
            description?: string | null;
            emails?:
              | {
                  email?: string | null;
                  id?: string | null;
                }[]
              | null;
            phoneNumbers?:
              | {
                  phone_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            faxNumbers?:
              | {
                  fax_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            siteName?: string | null;
            locale?: string | null;
            alternateLocale?:
              | {
                  alternate_locale?: string | null;
                  id?: string | null;
                }[]
              | null;
            images?: (number | Media)[] | null;
            audio?: (number | Media)[] | null;
            videos?: (number | Media)[] | null;
            url?: string | null;
            countryName?: string | null;
            ttl?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'OpenGraphWebsite';
          }
        | {
            type?: string | null;
            determiner?: ('a' | 'an' | 'the' | 'auto' | '') | null;
            title?: {
              default?: string | null;
              template?: string | null;
              absolute?: string | null;
            };
            description?: string | null;
            emails?:
              | {
                  email?: string | null;
                  id?: string | null;
                }[]
              | null;
            phoneNumbers?:
              | {
                  phone_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            faxNumbers?:
              | {
                  fax_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            siteName?: string | null;
            locale?: string | null;
            alternateLocale?:
              | {
                  alternate_locale?: string | null;
                  id?: string | null;
                }[]
              | null;
            images?: (number | Media)[] | null;
            audio?: (number | Media)[] | null;
            videos?: (number | Media)[] | null;
            url?: string | null;
            countryName?: string | null;
            ttl?: number | null;
            publishedTime?: string | null;
            modifiedTime?: string | null;
            expirationTime?: string | null;
            authors?: (number | User)[] | null;
            section?: string | null;
            tags?: (number | Tag)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'OpenGraphArticle';
          }
        | {
            type?: string | null;
            determiner?: ('a' | 'an' | 'the' | 'auto' | '') | null;
            title?: {
              default?: string | null;
              template?: string | null;
              absolute?: string | null;
            };
            description?: string | null;
            emails?:
              | {
                  email?: string | null;
                  id?: string | null;
                }[]
              | null;
            phoneNumbers?:
              | {
                  phone_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            faxNumbers?:
              | {
                  fax_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            siteName?: string | null;
            locale?: string | null;
            alternateLocale?:
              | {
                  alternate_locale?: string | null;
                  id?: string | null;
                }[]
              | null;
            images?: (number | Media)[] | null;
            audio?: (number | Media)[] | null;
            videos?: (number | Media)[] | null;
            url?: string | null;
            countryName?: string | null;
            ttl?: number | null;
            isbn?: number | null;
            releaseDate?: string | null;
            authors?: (number | User)[] | null;
            tags?: (number | Tag)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'OpenGraphBook';
          }
        | {
            type?: string | null;
            determiner?: ('a' | 'an' | 'the' | 'auto' | '') | null;
            title?: {
              default?: string | null;
              template?: string | null;
              absolute?: string | null;
            };
            description?: string | null;
            emails?:
              | {
                  email?: string | null;
                  id?: string | null;
                }[]
              | null;
            phoneNumbers?:
              | {
                  phone_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            faxNumbers?:
              | {
                  fax_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            siteName?: string | null;
            locale?: string | null;
            alternateLocale?:
              | {
                  alternate_locale?: string | null;
                  id?: string | null;
                }[]
              | null;
            images?: (number | Media)[] | null;
            audio?: (number | Media)[] | null;
            videos?: (number | Media)[] | null;
            url?: string | null;
            countryName?: string | null;
            ttl?: number | null;
            firstName?: string | null;
            lastName?: string | null;
            username?: string | null;
            gender?: ('male' | 'female') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'OpenGraphProfile';
          }
        | {
            type?: string | null;
            determiner?: ('a' | 'an' | 'the' | 'auto' | '') | null;
            title?: {
              default?: string | null;
              template?: string | null;
              absolute?: string | null;
            };
            description?: string | null;
            emails?:
              | {
                  email?: string | null;
                  id?: string | null;
                }[]
              | null;
            phoneNumbers?:
              | {
                  phone_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            faxNumbers?:
              | {
                  fax_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            siteName?: string | null;
            locale?: string | null;
            alternateLocale?:
              | {
                  alternate_locale?: string | null;
                  id?: string | null;
                }[]
              | null;
            images?: (number | Media)[] | null;
            audio?: (number | Media)[] | null;
            videos?: (number | Media)[] | null;
            url?: string | null;
            countryName?: string | null;
            ttl?: number | null;
            duration?: number | null;
            albums?:
              | {
                  album?: string | null;
                  id?: string | null;
                }[]
              | null;
            musicians?:
              | {
                  musician?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'OpenGraphMusicSong';
          }
        | {
            type?: string | null;
            determiner?: ('a' | 'an' | 'the' | 'auto' | '') | null;
            title?: {
              default?: string | null;
              template?: string | null;
              absolute?: string | null;
            };
            description?: string | null;
            emails?:
              | {
                  email?: string | null;
                  id?: string | null;
                }[]
              | null;
            phoneNumbers?:
              | {
                  phone_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            faxNumbers?:
              | {
                  fax_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            siteName?: string | null;
            locale?: string | null;
            alternateLocale?:
              | {
                  alternate_locale?: string | null;
                  id?: string | null;
                }[]
              | null;
            images?: (number | Media)[] | null;
            audio?: (number | Media)[] | null;
            videos?: (number | Media)[] | null;
            url?: string | null;
            countryName?: string | null;
            ttl?: number | null;
            songs?:
              | {
                  song?: string | null;
                  id?: string | null;
                }[]
              | null;
            musicians?:
              | {
                  musician?: string | null;
                  id?: string | null;
                }[]
              | null;
            releaseDate?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'OpenGraphMusicAlbum';
          }
        | {
            type?: string | null;
            determiner?: ('a' | 'an' | 'the' | 'auto' | '') | null;
            title?: {
              default?: string | null;
              template?: string | null;
              absolute?: string | null;
            };
            description?: string | null;
            emails?:
              | {
                  email?: string | null;
                  id?: string | null;
                }[]
              | null;
            phoneNumbers?:
              | {
                  phone_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            faxNumbers?:
              | {
                  fax_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            siteName?: string | null;
            locale?: string | null;
            alternateLocale?:
              | {
                  alternate_locale?: string | null;
                  id?: string | null;
                }[]
              | null;
            images?: (number | Media)[] | null;
            audio?: (number | Media)[] | null;
            videos?: (number | Media)[] | null;
            url?: string | null;
            countryName?: string | null;
            ttl?: number | null;
            songs?:
              | {
                  song?: string | null;
                  id?: string | null;
                }[]
              | null;
            creators?:
              | {
                  creator?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'OpenGraphMusicPlaylist';
          }
        | {
            type?: string | null;
            determiner?: ('a' | 'an' | 'the' | 'auto' | '') | null;
            title?: {
              default?: string | null;
              template?: string | null;
              absolute?: string | null;
            };
            description?: string | null;
            emails?:
              | {
                  email?: string | null;
                  id?: string | null;
                }[]
              | null;
            phoneNumbers?:
              | {
                  phone_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            faxNumbers?:
              | {
                  fax_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            siteName?: string | null;
            locale?: string | null;
            alternateLocale?:
              | {
                  alternate_locale?: string | null;
                  id?: string | null;
                }[]
              | null;
            images?: (number | Media)[] | null;
            audio?: (number | Media)[] | null;
            videos?: (number | Media)[] | null;
            url?: string | null;
            countryName?: string | null;
            ttl?: number | null;
            creators?:
              | {
                  creator?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'OpenGraphRadioStation';
          }
        | {
            type?: string | null;
            determiner?: ('a' | 'an' | 'the' | 'auto' | '') | null;
            title?: {
              default?: string | null;
              template?: string | null;
              absolute?: string | null;
            };
            description?: string | null;
            emails?:
              | {
                  email?: string | null;
                  id?: string | null;
                }[]
              | null;
            phoneNumbers?:
              | {
                  phone_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            faxNumbers?:
              | {
                  fax_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            siteName?: string | null;
            locale?: string | null;
            alternateLocale?:
              | {
                  alternate_locale?: string | null;
                  id?: string | null;
                }[]
              | null;
            images?: (number | Media)[] | null;
            audio?: (number | Media)[] | null;
            videos?: (number | Media)[] | null;
            url?: string | null;
            countryName?: string | null;
            ttl?: number | null;
            actors?:
              | {
                  actor?: string | null;
                  id?: string | null;
                }[]
              | null;
            directors?:
              | {
                  director?: string | null;
                  id?: string | null;
                }[]
              | null;
            writers?:
              | {
                  writer?: string | null;
                  id?: string | null;
                }[]
              | null;
            duration?: number | null;
            releaseDate?: string | null;
            tags?: (number | Tag)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'OpenGraphVideoMovie';
          }
        | {
            type?: string | null;
            determiner?: ('a' | 'an' | 'the' | 'auto' | '') | null;
            title?: {
              default?: string | null;
              template?: string | null;
              absolute?: string | null;
            };
            description?: string | null;
            emails?:
              | {
                  email?: string | null;
                  id?: string | null;
                }[]
              | null;
            phoneNumbers?:
              | {
                  phone_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            faxNumbers?:
              | {
                  fax_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            siteName?: string | null;
            locale?: string | null;
            alternateLocale?:
              | {
                  alternate_locale?: string | null;
                  id?: string | null;
                }[]
              | null;
            images?: (number | Media)[] | null;
            audio?: (number | Media)[] | null;
            videos?: (number | Media)[] | null;
            url?: string | null;
            countryName?: string | null;
            ttl?: number | null;
            actors?:
              | {
                  actor?: string | null;
                  id?: string | null;
                }[]
              | null;
            directors?:
              | {
                  director?: string | null;
                  id?: string | null;
                }[]
              | null;
            writers?:
              | {
                  writer?: string | null;
                  id?: string | null;
                }[]
              | null;
            duration?: number | null;
            releaseDate?: string | null;
            tags?: (number | Tag)[] | null;
            series?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'OpenGraphVideoEpisode';
          }
        | {
            type?: string | null;
            determiner?: ('a' | 'an' | 'the' | 'auto' | '') | null;
            title?: {
              default?: string | null;
              template?: string | null;
              absolute?: string | null;
            };
            description?: string | null;
            emails?:
              | {
                  email?: string | null;
                  id?: string | null;
                }[]
              | null;
            phoneNumbers?:
              | {
                  phone_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            faxNumbers?:
              | {
                  fax_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            siteName?: string | null;
            locale?: string | null;
            alternateLocale?:
              | {
                  alternate_locale?: string | null;
                  id?: string | null;
                }[]
              | null;
            images?: (number | Media)[] | null;
            audio?: (number | Media)[] | null;
            videos?: (number | Media)[] | null;
            url?: string | null;
            countryName?: string | null;
            ttl?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'OpenGraphVideoTVShow';
          }
        | {
            type?: string | null;
            determiner?: ('a' | 'an' | 'the' | 'auto' | '') | null;
            title?: {
              default?: string | null;
              template?: string | null;
              absolute?: string | null;
            };
            description?: string | null;
            emails?:
              | {
                  email?: string | null;
                  id?: string | null;
                }[]
              | null;
            phoneNumbers?:
              | {
                  phone_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            faxNumbers?:
              | {
                  fax_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            siteName?: string | null;
            locale?: string | null;
            alternateLocale?:
              | {
                  alternate_locale?: string | null;
                  id?: string | null;
                }[]
              | null;
            images?: (number | Media)[] | null;
            audio?: (number | Media)[] | null;
            videos?: (number | Media)[] | null;
            url?: string | null;
            countryName?: string | null;
            ttl?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'OpenGraphVideoOther';
          }
        | {
            determiner?: ('a' | 'an' | 'the' | 'auto' | '') | null;
            title?: {
              default?: string | null;
              template?: string | null;
              absolute?: string | null;
            };
            description?: string | null;
            emails?:
              | {
                  email?: string | null;
                  id?: string | null;
                }[]
              | null;
            phoneNumbers?:
              | {
                  phone_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            faxNumbers?:
              | {
                  fax_number?: string | null;
                  id?: string | null;
                }[]
              | null;
            siteName?: string | null;
            locale?: string | null;
            alternateLocale?:
              | {
                  alternate_locale?: string | null;
                  id?: string | null;
                }[]
              | null;
            images?: (number | Media)[] | null;
            audio?: (number | Media)[] | null;
            videos?: (number | Media)[] | null;
            url?: string | null;
            countryName?: string | null;
            ttl?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'OpenGraphMetadata';
          }
      )[]
    | null;
  twitter?:
    | (
        | {
            card?: string | null;
            site?: string | null;
            siteId?: string | null;
            creator?: string | null;
            creatorId?: string | null;
            description?: string | null;
            title?: {
              default?: string | null;
              template?: string | null;
              absolute?: string | null;
            };
            images?: (number | Media)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'TwitterSummary';
          }
        | {
            card?: string | null;
            site?: string | null;
            siteId?: string | null;
            creator?: string | null;
            creatorId?: string | null;
            description?: string | null;
            title?: {
              default?: string | null;
              template?: string | null;
              absolute?: string | null;
            };
            images?: (number | Media)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'TwitterSummaryLargeImage';
          }
        | {
            card?: string | null;
            site?: string | null;
            siteId?: string | null;
            creator?: string | null;
            creatorId?: string | null;
            description?: string | null;
            title?: {
              default?: string | null;
              template?: string | null;
              absolute?: string | null;
            };
            images?: (number | Media)[] | null;
            players?:
              | {
                  playerUrl?: string | null;
                  streamUrl?: string | null;
                  width?: number | null;
                  height?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'TwitterPlayer';
          }
        | {
            card?: string | null;
            site?: string | null;
            siteId?: string | null;
            creator?: string | null;
            creatorId?: string | null;
            description?: string | null;
            title?: {
              default?: string | null;
              template?: string | null;
              absolute?: string | null;
            };
            images?: (number | Media)[] | null;
            app?: {
              id?: {
                iphone?: string | null;
                ipad?: string | null;
                googleplay?: string | null;
              };
              url?: {
                iphone?: string | null;
                ipad?: string | null;
                googleplay?: string | null;
              };
              name?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'TwitterApp';
          }
        | {
            site?: string | null;
            siteId?: string | null;
            creator?: string | null;
            creatorId?: string | null;
            description?: string | null;
            title?: {
              default?: string | null;
              template?: string | null;
              absolute?: string | null;
            };
            images?: (number | Media)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'TwitterMetadata';
          }
      )[]
    | null;
  facebook?: {
    appId?: string | null;
    admins?:
      | {
          admin?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  pinterest?: {
    richPin?: string | null;
  };
  verification?: {
    google?:
      | {
          value?: string | null;
          id?: string | null;
        }[]
      | null;
    yahoo?:
      | {
          value?: string | null;
          id?: string | null;
        }[]
      | null;
    yandex?:
      | {
          value?: string | null;
          id?: string | null;
        }[]
      | null;
    me?:
      | {
          value?: string | null;
          id?: string | null;
        }[]
      | null;
    other?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  appleWebApp?: {
    capable?: boolean | null;
    title?: string | null;
    startupImage?: (number | Media)[] | null;
    statusBarStyle?: ('default' | 'black' | 'black-translucent') | null;
  };
  formatDetection?: {
    telephone?: boolean | null;
    date?: boolean | null;
    address?: boolean | null;
    email?: boolean | null;
    url?: boolean | null;
  };
  itunes?: {
    appId?: string | null;
    appArgument?: string | null;
  };
  abstract?: string | null;
  appLinks?: {
    ios?:
      | {
          url?: string | null;
          app_store_id?: string | null;
          app_name?: string | null;
          id?: string | null;
        }[]
      | null;
    iphone?:
      | {
          url?: string | null;
          app_store_id?: string | null;
          app_name?: string | null;
          id?: string | null;
        }[]
      | null;
    ipad?:
      | {
          url?: string | null;
          app_store_id?: string | null;
          app_name?: string | null;
          id?: string | null;
        }[]
      | null;
    android?:
      | {
          package?: string | null;
          url?: string | null;
          class?: string | null;
          app_name?: string | null;
          id?: string | null;
        }[]
      | null;
    windows_phone?:
      | {
          url?: string | null;
          app_id?: string | null;
          app_name?: string | null;
          id?: string | null;
        }[]
      | null;
    windows?:
      | {
          url?: string | null;
          app_id?: string | null;
          app_name?: string | null;
          id?: string | null;
        }[]
      | null;
    windows_universal?:
      | {
          url?: string | null;
          app_id?: string | null;
          app_name?: string | null;
          id?: string | null;
        }[]
      | null;
    web?:
      | {
          url?: string | null;
          should_fallback?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  archives?:
    | {
        archive?: string | null;
        id?: string | null;
      }[]
    | null;
  assets?:
    | {
        asset?: string | null;
        id?: string | null;
      }[]
    | null;
  bookmarks?:
    | {
        bookmark?: string | null;
        id?: string | null;
      }[]
    | null;
  pagination?: {
    previous?: string | null;
    next?: string | null;
  };
  category?: string | null;
  classification?: string | null;
  other?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "robots".
 */
export interface Robot {
  id: number;
  rules?:
    | {
        userAgents?:
          | {
              userAgent?: string | null;
              id?: string | null;
            }[]
          | null;
        allows?:
          | {
              allow?: string | null;
              id?: string | null;
            }[]
          | null;
        disallows?:
          | {
              disallow?: string | null;
              id?: string | null;
            }[]
          | null;
        crawlDelay?: number | null;
        id?: string | null;
      }[]
    | null;
  sitemaps?:
    | {
        sitemap?: string | null;
        id?: string | null;
      }[]
    | null;
  host?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifest".
 */
export interface Manifest {
  id: number;
  name?: string | null;
  short_name?: string | null;
  description?: string | null;
  start_url?: string | null;
  scope?: string | null;
  display?: ('fullscreen' | 'standalone' | 'minimal-ui' | 'browser') | null;
  orientation?:
    | (
        | 'any'
        | 'natural'
        | 'landscape'
        | 'portrait'
        | 'portrait-primary'
        | 'portrait-secondary'
        | 'landscape-primary'
        | 'landscape-secondary'
      )
    | null;
  theme_color?: string | null;
  background_color?: string | null;
  lang?: string | null;
  dir?: ('ltr' | 'rtl' | 'auto') | null;
  categories?: (number | Category)[] | null;
  icons?: (number | Media)[] | null;
  screenshots?: (number | Media)[] | null;
  shortcuts?:
    | {
        name?: string | null;
        short_name?: string | null;
        description?: string | null;
        url?: string | null;
        icons?: (number | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  prefer_related_applications?: boolean | null;
  related_applications?:
    | {
        platform?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  protocol_handlers?:
    | {
        protocol?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  share_target?: {
    action?: string | null;
    method?: ('GET' | 'POST') | null;
    enctype?: ('application/x-www-form-urlencoded' | 'multipart/form-data') | null;
    params?: {
      title?: string | null;
      text?: string | null;
      url?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sitemap".
 */
export interface Sitemap {
  id: number;
  pages?:
    | {
        url?: string | null;
        lastModified?: string | null;
        changeFrequency?: ('always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never') | null;
        priority?: number | null;
        alternates?: {
          languages?:
            | {
                language?: string | null;
                url?: string | null;
                id?: string | null;
              }[]
            | null;
        };
        images?: (number | Media)[] | null;
        videos?: (number | Media)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'custom';
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metadata_select".
 */
export interface MetadataSelect<T extends boolean = true> {
  metadataBase?: T;
  title?:
    | T
    | {
        default?: T;
        template?: T;
        absolute?: T;
      };
  description?: T;
  applicationName?: T;
  authors?: T;
  generator?: T;
  keywords?: T;
  referrer?: T;
  creator?: T;
  publisher?: T;
  robots?: T;
  alternates?:
    | T
    | {
        canonical?: T;
        languages?:
          | T
          | {
              language?: T;
              url?: T;
              id?: T;
            };
        media?:
          | T
          | {
              medium?: T;
              url?: T;
              id?: T;
            };
        types?:
          | T
          | {
              type?: T;
              url?: T;
              id?: T;
            };
      };
  icons?: T;
  manifest?: T;
  openGraph?:
    | T
    | {
        OpenGraphWebsite?:
          | T
          | {
              type?: T;
              determiner?: T;
              title?:
                | T
                | {
                    default?: T;
                    template?: T;
                    absolute?: T;
                  };
              description?: T;
              emails?:
                | T
                | {
                    email?: T;
                    id?: T;
                  };
              phoneNumbers?:
                | T
                | {
                    phone_number?: T;
                    id?: T;
                  };
              faxNumbers?:
                | T
                | {
                    fax_number?: T;
                    id?: T;
                  };
              siteName?: T;
              locale?: T;
              alternateLocale?:
                | T
                | {
                    alternate_locale?: T;
                    id?: T;
                  };
              images?: T;
              audio?: T;
              videos?: T;
              url?: T;
              countryName?: T;
              ttl?: T;
              id?: T;
              blockName?: T;
            };
        OpenGraphArticle?:
          | T
          | {
              type?: T;
              determiner?: T;
              title?:
                | T
                | {
                    default?: T;
                    template?: T;
                    absolute?: T;
                  };
              description?: T;
              emails?:
                | T
                | {
                    email?: T;
                    id?: T;
                  };
              phoneNumbers?:
                | T
                | {
                    phone_number?: T;
                    id?: T;
                  };
              faxNumbers?:
                | T
                | {
                    fax_number?: T;
                    id?: T;
                  };
              siteName?: T;
              locale?: T;
              alternateLocale?:
                | T
                | {
                    alternate_locale?: T;
                    id?: T;
                  };
              images?: T;
              audio?: T;
              videos?: T;
              url?: T;
              countryName?: T;
              ttl?: T;
              publishedTime?: T;
              modifiedTime?: T;
              expirationTime?: T;
              authors?: T;
              section?: T;
              tags?: T;
              id?: T;
              blockName?: T;
            };
        OpenGraphBook?:
          | T
          | {
              type?: T;
              determiner?: T;
              title?:
                | T
                | {
                    default?: T;
                    template?: T;
                    absolute?: T;
                  };
              description?: T;
              emails?:
                | T
                | {
                    email?: T;
                    id?: T;
                  };
              phoneNumbers?:
                | T
                | {
                    phone_number?: T;
                    id?: T;
                  };
              faxNumbers?:
                | T
                | {
                    fax_number?: T;
                    id?: T;
                  };
              siteName?: T;
              locale?: T;
              alternateLocale?:
                | T
                | {
                    alternate_locale?: T;
                    id?: T;
                  };
              images?: T;
              audio?: T;
              videos?: T;
              url?: T;
              countryName?: T;
              ttl?: T;
              isbn?: T;
              releaseDate?: T;
              authors?: T;
              tags?: T;
              id?: T;
              blockName?: T;
            };
        OpenGraphProfile?:
          | T
          | {
              type?: T;
              determiner?: T;
              title?:
                | T
                | {
                    default?: T;
                    template?: T;
                    absolute?: T;
                  };
              description?: T;
              emails?:
                | T
                | {
                    email?: T;
                    id?: T;
                  };
              phoneNumbers?:
                | T
                | {
                    phone_number?: T;
                    id?: T;
                  };
              faxNumbers?:
                | T
                | {
                    fax_number?: T;
                    id?: T;
                  };
              siteName?: T;
              locale?: T;
              alternateLocale?:
                | T
                | {
                    alternate_locale?: T;
                    id?: T;
                  };
              images?: T;
              audio?: T;
              videos?: T;
              url?: T;
              countryName?: T;
              ttl?: T;
              firstName?: T;
              lastName?: T;
              username?: T;
              gender?: T;
              id?: T;
              blockName?: T;
            };
        OpenGraphMusicSong?:
          | T
          | {
              type?: T;
              determiner?: T;
              title?:
                | T
                | {
                    default?: T;
                    template?: T;
                    absolute?: T;
                  };
              description?: T;
              emails?:
                | T
                | {
                    email?: T;
                    id?: T;
                  };
              phoneNumbers?:
                | T
                | {
                    phone_number?: T;
                    id?: T;
                  };
              faxNumbers?:
                | T
                | {
                    fax_number?: T;
                    id?: T;
                  };
              siteName?: T;
              locale?: T;
              alternateLocale?:
                | T
                | {
                    alternate_locale?: T;
                    id?: T;
                  };
              images?: T;
              audio?: T;
              videos?: T;
              url?: T;
              countryName?: T;
              ttl?: T;
              duration?: T;
              albums?:
                | T
                | {
                    album?: T;
                    id?: T;
                  };
              musicians?:
                | T
                | {
                    musician?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        OpenGraphMusicAlbum?:
          | T
          | {
              type?: T;
              determiner?: T;
              title?:
                | T
                | {
                    default?: T;
                    template?: T;
                    absolute?: T;
                  };
              description?: T;
              emails?:
                | T
                | {
                    email?: T;
                    id?: T;
                  };
              phoneNumbers?:
                | T
                | {
                    phone_number?: T;
                    id?: T;
                  };
              faxNumbers?:
                | T
                | {
                    fax_number?: T;
                    id?: T;
                  };
              siteName?: T;
              locale?: T;
              alternateLocale?:
                | T
                | {
                    alternate_locale?: T;
                    id?: T;
                  };
              images?: T;
              audio?: T;
              videos?: T;
              url?: T;
              countryName?: T;
              ttl?: T;
              songs?:
                | T
                | {
                    song?: T;
                    id?: T;
                  };
              musicians?:
                | T
                | {
                    musician?: T;
                    id?: T;
                  };
              releaseDate?: T;
              id?: T;
              blockName?: T;
            };
        OpenGraphMusicPlaylist?:
          | T
          | {
              type?: T;
              determiner?: T;
              title?:
                | T
                | {
                    default?: T;
                    template?: T;
                    absolute?: T;
                  };
              description?: T;
              emails?:
                | T
                | {
                    email?: T;
                    id?: T;
                  };
              phoneNumbers?:
                | T
                | {
                    phone_number?: T;
                    id?: T;
                  };
              faxNumbers?:
                | T
                | {
                    fax_number?: T;
                    id?: T;
                  };
              siteName?: T;
              locale?: T;
              alternateLocale?:
                | T
                | {
                    alternate_locale?: T;
                    id?: T;
                  };
              images?: T;
              audio?: T;
              videos?: T;
              url?: T;
              countryName?: T;
              ttl?: T;
              songs?:
                | T
                | {
                    song?: T;
                    id?: T;
                  };
              creators?:
                | T
                | {
                    creator?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        OpenGraphRadioStation?:
          | T
          | {
              type?: T;
              determiner?: T;
              title?:
                | T
                | {
                    default?: T;
                    template?: T;
                    absolute?: T;
                  };
              description?: T;
              emails?:
                | T
                | {
                    email?: T;
                    id?: T;
                  };
              phoneNumbers?:
                | T
                | {
                    phone_number?: T;
                    id?: T;
                  };
              faxNumbers?:
                | T
                | {
                    fax_number?: T;
                    id?: T;
                  };
              siteName?: T;
              locale?: T;
              alternateLocale?:
                | T
                | {
                    alternate_locale?: T;
                    id?: T;
                  };
              images?: T;
              audio?: T;
              videos?: T;
              url?: T;
              countryName?: T;
              ttl?: T;
              creators?:
                | T
                | {
                    creator?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        OpenGraphVideoMovie?:
          | T
          | {
              type?: T;
              determiner?: T;
              title?:
                | T
                | {
                    default?: T;
                    template?: T;
                    absolute?: T;
                  };
              description?: T;
              emails?:
                | T
                | {
                    email?: T;
                    id?: T;
                  };
              phoneNumbers?:
                | T
                | {
                    phone_number?: T;
                    id?: T;
                  };
              faxNumbers?:
                | T
                | {
                    fax_number?: T;
                    id?: T;
                  };
              siteName?: T;
              locale?: T;
              alternateLocale?:
                | T
                | {
                    alternate_locale?: T;
                    id?: T;
                  };
              images?: T;
              audio?: T;
              videos?: T;
              url?: T;
              countryName?: T;
              ttl?: T;
              actors?:
                | T
                | {
                    actor?: T;
                    id?: T;
                  };
              directors?:
                | T
                | {
                    director?: T;
                    id?: T;
                  };
              writers?:
                | T
                | {
                    writer?: T;
                    id?: T;
                  };
              duration?: T;
              releaseDate?: T;
              tags?: T;
              id?: T;
              blockName?: T;
            };
        OpenGraphVideoEpisode?:
          | T
          | {
              type?: T;
              determiner?: T;
              title?:
                | T
                | {
                    default?: T;
                    template?: T;
                    absolute?: T;
                  };
              description?: T;
              emails?:
                | T
                | {
                    email?: T;
                    id?: T;
                  };
              phoneNumbers?:
                | T
                | {
                    phone_number?: T;
                    id?: T;
                  };
              faxNumbers?:
                | T
                | {
                    fax_number?: T;
                    id?: T;
                  };
              siteName?: T;
              locale?: T;
              alternateLocale?:
                | T
                | {
                    alternate_locale?: T;
                    id?: T;
                  };
              images?: T;
              audio?: T;
              videos?: T;
              url?: T;
              countryName?: T;
              ttl?: T;
              actors?:
                | T
                | {
                    actor?: T;
                    id?: T;
                  };
              directors?:
                | T
                | {
                    director?: T;
                    id?: T;
                  };
              writers?:
                | T
                | {
                    writer?: T;
                    id?: T;
                  };
              duration?: T;
              releaseDate?: T;
              tags?: T;
              series?: T;
              id?: T;
              blockName?: T;
            };
        OpenGraphVideoTVShow?:
          | T
          | {
              type?: T;
              determiner?: T;
              title?:
                | T
                | {
                    default?: T;
                    template?: T;
                    absolute?: T;
                  };
              description?: T;
              emails?:
                | T
                | {
                    email?: T;
                    id?: T;
                  };
              phoneNumbers?:
                | T
                | {
                    phone_number?: T;
                    id?: T;
                  };
              faxNumbers?:
                | T
                | {
                    fax_number?: T;
                    id?: T;
                  };
              siteName?: T;
              locale?: T;
              alternateLocale?:
                | T
                | {
                    alternate_locale?: T;
                    id?: T;
                  };
              images?: T;
              audio?: T;
              videos?: T;
              url?: T;
              countryName?: T;
              ttl?: T;
              id?: T;
              blockName?: T;
            };
        OpenGraphVideoOther?:
          | T
          | {
              type?: T;
              determiner?: T;
              title?:
                | T
                | {
                    default?: T;
                    template?: T;
                    absolute?: T;
                  };
              description?: T;
              emails?:
                | T
                | {
                    email?: T;
                    id?: T;
                  };
              phoneNumbers?:
                | T
                | {
                    phone_number?: T;
                    id?: T;
                  };
              faxNumbers?:
                | T
                | {
                    fax_number?: T;
                    id?: T;
                  };
              siteName?: T;
              locale?: T;
              alternateLocale?:
                | T
                | {
                    alternate_locale?: T;
                    id?: T;
                  };
              images?: T;
              audio?: T;
              videos?: T;
              url?: T;
              countryName?: T;
              ttl?: T;
              id?: T;
              blockName?: T;
            };
        OpenGraphMetadata?:
          | T
          | {
              determiner?: T;
              title?:
                | T
                | {
                    default?: T;
                    template?: T;
                    absolute?: T;
                  };
              description?: T;
              emails?:
                | T
                | {
                    email?: T;
                    id?: T;
                  };
              phoneNumbers?:
                | T
                | {
                    phone_number?: T;
                    id?: T;
                  };
              faxNumbers?:
                | T
                | {
                    fax_number?: T;
                    id?: T;
                  };
              siteName?: T;
              locale?: T;
              alternateLocale?:
                | T
                | {
                    alternate_locale?: T;
                    id?: T;
                  };
              images?: T;
              audio?: T;
              videos?: T;
              url?: T;
              countryName?: T;
              ttl?: T;
              id?: T;
              blockName?: T;
            };
      };
  twitter?:
    | T
    | {
        TwitterSummary?:
          | T
          | {
              card?: T;
              site?: T;
              siteId?: T;
              creator?: T;
              creatorId?: T;
              description?: T;
              title?:
                | T
                | {
                    default?: T;
                    template?: T;
                    absolute?: T;
                  };
              images?: T;
              id?: T;
              blockName?: T;
            };
        TwitterSummaryLargeImage?:
          | T
          | {
              card?: T;
              site?: T;
              siteId?: T;
              creator?: T;
              creatorId?: T;
              description?: T;
              title?:
                | T
                | {
                    default?: T;
                    template?: T;
                    absolute?: T;
                  };
              images?: T;
              id?: T;
              blockName?: T;
            };
        TwitterPlayer?:
          | T
          | {
              card?: T;
              site?: T;
              siteId?: T;
              creator?: T;
              creatorId?: T;
              description?: T;
              title?:
                | T
                | {
                    default?: T;
                    template?: T;
                    absolute?: T;
                  };
              images?: T;
              players?:
                | T
                | {
                    playerUrl?: T;
                    streamUrl?: T;
                    width?: T;
                    height?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        TwitterApp?:
          | T
          | {
              card?: T;
              site?: T;
              siteId?: T;
              creator?: T;
              creatorId?: T;
              description?: T;
              title?:
                | T
                | {
                    default?: T;
                    template?: T;
                    absolute?: T;
                  };
              images?: T;
              app?:
                | T
                | {
                    id?:
                      | T
                      | {
                          iphone?: T;
                          ipad?: T;
                          googleplay?: T;
                        };
                    url?:
                      | T
                      | {
                          iphone?: T;
                          ipad?: T;
                          googleplay?: T;
                        };
                    name?: T;
                  };
              id?: T;
              blockName?: T;
            };
        TwitterMetadata?:
          | T
          | {
              site?: T;
              siteId?: T;
              creator?: T;
              creatorId?: T;
              description?: T;
              title?:
                | T
                | {
                    default?: T;
                    template?: T;
                    absolute?: T;
                  };
              images?: T;
              id?: T;
              blockName?: T;
            };
      };
  facebook?:
    | T
    | {
        appId?: T;
        admins?:
          | T
          | {
              admin?: T;
              id?: T;
            };
      };
  pinterest?:
    | T
    | {
        richPin?: T;
      };
  verification?:
    | T
    | {
        google?:
          | T
          | {
              value?: T;
              id?: T;
            };
        yahoo?:
          | T
          | {
              value?: T;
              id?: T;
            };
        yandex?:
          | T
          | {
              value?: T;
              id?: T;
            };
        me?:
          | T
          | {
              value?: T;
              id?: T;
            };
        other?: T;
      };
  appleWebApp?:
    | T
    | {
        capable?: T;
        title?: T;
        startupImage?: T;
        statusBarStyle?: T;
      };
  formatDetection?:
    | T
    | {
        telephone?: T;
        date?: T;
        address?: T;
        email?: T;
        url?: T;
      };
  itunes?:
    | T
    | {
        appId?: T;
        appArgument?: T;
      };
  abstract?: T;
  appLinks?:
    | T
    | {
        ios?:
          | T
          | {
              url?: T;
              app_store_id?: T;
              app_name?: T;
              id?: T;
            };
        iphone?:
          | T
          | {
              url?: T;
              app_store_id?: T;
              app_name?: T;
              id?: T;
            };
        ipad?:
          | T
          | {
              url?: T;
              app_store_id?: T;
              app_name?: T;
              id?: T;
            };
        android?:
          | T
          | {
              package?: T;
              url?: T;
              class?: T;
              app_name?: T;
              id?: T;
            };
        windows_phone?:
          | T
          | {
              url?: T;
              app_id?: T;
              app_name?: T;
              id?: T;
            };
        windows?:
          | T
          | {
              url?: T;
              app_id?: T;
              app_name?: T;
              id?: T;
            };
        windows_universal?:
          | T
          | {
              url?: T;
              app_id?: T;
              app_name?: T;
              id?: T;
            };
        web?:
          | T
          | {
              url?: T;
              should_fallback?: T;
              id?: T;
            };
      };
  archives?:
    | T
    | {
        archive?: T;
        id?: T;
      };
  assets?:
    | T
    | {
        asset?: T;
        id?: T;
      };
  bookmarks?:
    | T
    | {
        bookmark?: T;
        id?: T;
      };
  pagination?:
    | T
    | {
        previous?: T;
        next?: T;
      };
  category?: T;
  classification?: T;
  other?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "robots_select".
 */
export interface RobotsSelect<T extends boolean = true> {
  rules?:
    | T
    | {
        userAgents?:
          | T
          | {
              userAgent?: T;
              id?: T;
            };
        allows?:
          | T
          | {
              allow?: T;
              id?: T;
            };
        disallows?:
          | T
          | {
              disallow?: T;
              id?: T;
            };
        crawlDelay?: T;
        id?: T;
      };
  sitemaps?:
    | T
    | {
        sitemap?: T;
        id?: T;
      };
  host?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifest_select".
 */
export interface ManifestSelect<T extends boolean = true> {
  name?: T;
  short_name?: T;
  description?: T;
  start_url?: T;
  scope?: T;
  display?: T;
  orientation?: T;
  theme_color?: T;
  background_color?: T;
  lang?: T;
  dir?: T;
  categories?: T;
  icons?: T;
  screenshots?: T;
  shortcuts?:
    | T
    | {
        name?: T;
        short_name?: T;
        description?: T;
        url?: T;
        icons?: T;
        id?: T;
      };
  prefer_related_applications?: T;
  related_applications?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  protocol_handlers?:
    | T
    | {
        protocol?: T;
        url?: T;
        id?: T;
      };
  share_target?:
    | T
    | {
        action?: T;
        method?: T;
        enctype?: T;
        params?:
          | T
          | {
              title?: T;
              text?: T;
              url?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sitemap_select".
 */
export interface SitemapSelect<T extends boolean = true> {
  pages?:
    | T
    | {
        custom?:
          | T
          | {
              url?: T;
              lastModified?: T;
              changeFrequency?: T;
              priority?: T;
              alternates?:
                | T
                | {
                    languages?:
                      | T
                      | {
                          language?: T;
                          url?: T;
                          id?: T;
                        };
                  };
              images?: T;
              videos?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}